services:
  - type: static
    name: situation-citerne-gasoil
    env: static
    buildCommand: pnpm install && pnpm build
    staticPublishPath: ./dist/public
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - path: /*
        destination: /index.html
