services:
  - type: web
    name: situation-citerne-gasoil
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build:full
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
